name:                test-v20200427
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: docs
  dependencies:
  - extra

executables:
  preprocess:
    main:                Preprocess.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cmark-gfm
    - directory
    - filepath
    - text

tests:
  test-v20200427-test:
    main:                Doctest.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - test-v20200427
    - doctest
