version: 2.1
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-15.7
    steps:
      - checkout
      - restore_cache:
          name: キャッシュされた依存関係を復元
          keys:
            - cci-demo-haskell-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
      - run:
          name: 依存関係を解決・更新
          command: stack setup
      - run:
          name: preprocessをビルド
          command: stack build
      - run:
          name: preprocessを実行
          command: stack exec preprocess
      - run:
          name: テストを実行
          command: stack test
      - run:
          name: 実行可能ファイルをインストール
          command: stack install
      - save_cache:
          name: 依存関係をキャッシュ
          key: cci-demo-haskell-v1-{{ checksum "package.yaml" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
